---
apiVersion: v1
kind: Namespace
metadata:
  name: minions
  
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minions
  labels:
    app: minio
type: Opaque
data:
  MINIO_ROOT_USER: cm9vdA==
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQ=